---
schemas:
- name: promo_codes
  topic:
    name: movr.public.promo_codes
    numPartitions: 1
    replicationFactor: 3
    config:
    - key: max.message.bytes
      value: "128000"
  changeFeed:
    fullTableName: movr.public.promo_codes
    options:
    - full_table_name
    - on_error = 'pause'
    - protect_data_from_gc_on_pause
    - updated
  sql:
    queryType:
      none:
        immutableColumns:
        - name: code
          type: varchar
  elasticsearch:
    index:
      name: promo_codes
      create: true
    mapping:
      settings:
        index.requests.cache.enable: true
        index:
          number_of_shards: 3
          number_of_replicas: 2
        analysis:
          normalizer:
            lowerasciinormalizer:
              type: custom
              filter:
              - lowercase
              - asciifolding
      mappings:
        dynamic_templates:
        - string_as_keyword:
            match_mapping_type: string
            match: '*'
            mapping:
              type: keyword
              normalizer: lowerasciinormalizer
        properties:
          code:
            normalizer: lowerasciinormalizer
            type: keyword
          description:
            normalizer: lowerasciinormalizer
            type: keyword
          creation_time:
            type: date
          rules:
            type: object
- name: user_promo_codes
  topic:
    name: movr.public.user_promo_codes
    numPartitions: 1
    replicationFactor: 3
    config:
    - key: max.message.bytes
      value: "128000"
  changeFeed:
    fullTableName: movr.public.user_promo_codes
    options:
    - full_table_name
    - on_error = 'pause'
    - protect_data_from_gc_on_pause
    - updated
  sql:
    queryType:
      none:
        immutableColumns:
        - name: user_id
          type: uuid
  elasticsearch:
    index:
      name: user_promo_codes
      create: true
    mapping:
      settings:
        index.requests.cache.enable: true
        index:
          number_of_shards: 3
          number_of_replicas: 2
        analysis:
          normalizer:
            lowerasciinormalizer:
              type: custom
              filter:
              - lowercase
              - asciifolding
      mappings:
        dynamic_templates:
        - string_as_keyword:
            match_mapping_type: string
            match: '*'
            mapping:
              type: keyword
              normalizer: lowerasciinormalizer
        properties:
          city:
            normalizer: lowerasciinormalizer
            type: keyword
          user_id:
            type: keyword
          code:
            normalizer: lowerasciinormalizer
            type: keyword
          timestamp:
            type: date
          usage_count:
            type: integer
- name: users
  topic:
    name: movr.public.users
    numPartitions: 1
    replicationFactor: 3
    config:
    - key: max.message.bytes
      value: "128000"
  changeFeed:
    fullTableName: movr.public.users
    options:
    - full_table_name
    - on_error = 'pause'
    - protect_data_from_gc_on_pause
    - updated
  sql:
    queryType:
      none:
        immutableColumns:
        - name: code
          type: varchar
  elasticsearch:
    index:
      name: users
      create: true
    mapping:
      settings:
        index.requests.cache.enable: true
        index:
          number_of_shards: 3
          number_of_replicas: 2
        analysis:
          normalizer:
            lowerasciinormalizer:
              type: custom
              filter:
              - lowercase
              - asciifolding
      mappings:
        dynamic_templates:
        - string_as_keyword:
            match_mapping_type: string
            match: '*'
            mapping:
              type: keyword
              normalizer: lowerasciinormalizer
        properties:
          id:
            type: keyword
          city:
            normalizer: lowerasciinormalizer
            type: keyword
          name:
            normalizer: lowerasciinormalizer
            type: keyword
          address:
            normalizer: lowerasciinormalizer
            type: keyword
          credit_card:
            normalizer: lowerasciinormalizer
            type: keyword
- name: vehicle_location_histories
  topic:
    name: movr.public.vehicle_location_histories
    numPartitions: 1
    replicationFactor: 3
    config:
    - key: max.message.bytes
      value: "128000"
  changeFeed:
    fullTableName: movr.public.vehicle_location_histories
    options:
    - full_table_name
    - on_error = 'pause'
    - protect_data_from_gc_on_pause
    - updated
  sql:
    queryType:
      none:
        immutableColumns:
        - name: ride_id
          type: uuid
        - name: timestamp
          type: date
  elasticsearch:
    index:
        name: vehicle_location_histories
        create: true
    mapping:
      settings:
        index.requests.cache.enable: true
        index:
          number_of_shards: 3
          number_of_replicas: 2
        analysis:
          normalizer:
            lowerasciinormalizer:
              type: custom
              filter:
              - lowercase
              - asciifolding
      mappings:
        dynamic_templates:
        - string_as_keyword:
            match_mapping_type: string
            match: '*'
            mapping:
              type: keyword
              normalizer: lowerasciinormalizer
        properties:
          city:
            normalizer: lowerasciinormalizer
            type: keyword
          ride_id:
            type: keyword
          timestamp:
            type: date
          lat:
            type: float
          long:
            type: float
- name: vehicles
  topic:
    name: movr.public.vehicles
    numPartitions: 1
    replicationFactor: 3
    config:
    - key: max.message.bytes
      value: "128000"
  changeFeed:
    fullTableName: movr.public.vehicles
    options:
    - full_table_name
    - on_error = 'pause'
    - protect_data_from_gc_on_pause
    - updated
  sql:
    queryType:
      none:
        immutableColumns:
        - name: id
          type: uuid
  elasticsearch:
    index:
      name: vehicles
      create: true
      alias: vehicles_alias
    mapping:
      settings:
        index.requests.cache.enable: true
        index:
          number_of_shards: 3
          number_of_replicas: 2
        analysis:
          normalizer:
            lowerasciinormalizer:
              type: custom
              filter:
              - lowercase
              - asciifolding
      mappings:
        dynamic_templates:
        - string_as_keyword:
            match_mapping_type: string
            match: '*'
            mapping:
              type: keyword
              normalizer: lowerasciinormalizer
        properties:
          id:
            type: keyword
          city:
            normalizer: lowerasciinormalizer
            type: keyword
          type:
            normalizer: lowerasciinormalizer
            type: keyword
          owner_id:
            normalizer: lowerasciinormalizer
            type: keyword
          creation_time:
            type: date
          status:
            normalizer: lowerasciinormalizer
            type: keyword
          current_location:
            normalizer: lowerasciinormalizer
            type: keyword
          ext:
            type: object
- name: rides
  topic:
    name: movr.public.rides
    numPartitions: 1
    replicationFactor: 3
    config:
    - key: max.message.bytes
      value: "128000"
  changeFeed:
    fullTableName: movr.public.rides
    options:
    - full_table_name
    - on_error = 'pause'
    - protect_data_from_gc_on_pause
    - updated
  sql:
    queryType:
      advanced:
        immutableColumns:
        - name: id
          type: uuid
        query: "SELECT rides.id,rides.city,rides.vehicle_city,rides.rider_id,rides.vehicle_id,rides.start_address,rides.end_address,rides.start_time,rides.end_time,rides.revenue,vehicles.type FROM rides LEFT JOIN vehicles ON vehicles.id = rides.vehicle_id"
  elasticsearch:
    index:
      name: rides
      create: true
    mapping:
      settings:
        index.requests.cache.enable: true
        index:
          number_of_shards: 3
          number_of_replicas: 2
        analysis:
          normalizer:
            lowerasciinormalizer:
              type: custom
              filter:
              - lowercase
              - asciifolding
      mappings:
        dynamic_templates:
        - string_as_keyword:
            match_mapping_type: string
            match: '*'
            mapping:
              type: keyword
              normalizer: lowerasciinormalizer
        properties:
          id:
            type: keyword
          city:
            normalizer: lowerasciinormalizer
            type: keyword
          vehicle_city:
            normalizer: lowerasciinormalizer
            type: keyword
          rider_id:
            type: keyword
          vehicle_id:
            type: keyword
          start_address:
            normalizer: lowerasciinormalizer
            type: keyword
          end_address:
            normalizer: lowerasciinormalizer
            type: keyword
          start_time:
            type: date
          end_time:
            type: date
          revenue:
            type: float
          type:
            normalizer: lowerasciinormalizer
            type: keyword