---
schemas:
- name: promo_codes
  topic:
    name: movr.public.promo_codes
    numPartitions: 1
    replicationFactor: 3
    config:
    - key: max.message.bytes
      value: "128000"
  sql:
    type: plain
    query: SELECT * FROM promo_codes
  elasticsearch:
    index: promo_codes
    mapping:
      settings:
        index.requests.cache.enable: true
        index:
          number_of_shards: 3
          number_of_replicas: 2
        analysis:
          normalizer:
            lowerasciinormalizer:
              type: custom
              filter:
              - lowercase
              - asciifolding
      mappings:
        dynamic_templates:
        - string_as_keyword:
            match_mapping_type: string
            match: '*'
            mapping:
              type: keyword
              normalizer: lowerasciinormalizer
        properties:
          code:
            normalizer: lowerasciinormalizer
            type: keyword
          description:
            normalizer: lowerasciinormalizer
            type: keyword
          creation_time:
            type: date
          rules:
            normalizer: lowerasciinormalizer
            type: keyword
- name: user_promo_codes
  topic:
    name: movr.public.user_promo_codes
    numPartitions: 1
    replicationFactor: 3
    config:
    - key: max.message.bytes
      value: "128000"
  sql:
    type: plain
    query: SELECT * FROM user_promo_codes
  elasticsearch:
    index: user_promo_codes
    mapping:
      settings:
        index.requests.cache.enable: true
        index:
          number_of_shards: 3
          number_of_replicas: 2
        analysis:
          normalizer:
            lowerasciinormalizer:
              type: custom
              filter:
              - lowercase
              - asciifolding
      mappings:
        dynamic_templates:
        - string_as_keyword:
            match_mapping_type: string
            match: '*'
            mapping:
              type: keyword
              normalizer: lowerasciinormalizer
        properties:
          city:
            normalizer: lowerasciinormalizer
            type: keyword
          user_id:
            type: keyword
          code:
            normalizer: lowerasciinormalizer
            type: keyword
          timestamp:
            type: date
          usage_count:
            type: integer
- name: users
  topic:
    name: movr.public.users
    numPartitions: 1
    replicationFactor: 3
    config:
    - key: max.message.bytes
      value: "128000"
  sql:
    type: plain
    query: SELECT * FROM users
  elasticsearch:
    index: users
    mapping:
      settings:
        index.requests.cache.enable: true
        index:
          number_of_shards: 3
          number_of_replicas: 2
        analysis:
          normalizer:
            lowerasciinormalizer:
              type: custom
              filter:
              - lowercase
              - asciifolding
      mappings:
        dynamic_templates:
        - string_as_keyword:
            match_mapping_type: string
            match: '*'
            mapping:
              type: keyword
              normalizer: lowerasciinormalizer
        properties:
          id:
            type: keyword
          city:
            normalizer: lowerasciinormalizer
            type: keyword
          name:
            normalizer: lowerasciinormalizer
            type: keyword
          address:
            normalizer: lowerasciinormalizer
            type: keyword
          credit_card:
            normalizer: lowerasciinormalizer
            type: keyword
- name: vehicle_location_histories
  topic:
    name: movr.public.vehicle_location_histories
    numPartitions: 1
    replicationFactor: 3
    config:
    - key: max.message.bytes
      value: "128000"
  sql:
    type: plain
    query: SELECT * FROM vehicle_location_histories
  elasticsearch:
    index: vehicle_location_histories
    mapping:
      settings:
        index.requests.cache.enable: true
        index:
          number_of_shards: 3
          number_of_replicas: 2
        analysis:
          normalizer:
            lowerasciinormalizer:
              type: custom
              filter:
              - lowercase
              - asciifolding
      mappings:
        dynamic_templates:
        - string_as_keyword:
            match_mapping_type: string
            match: '*'
            mapping:
              type: keyword
              normalizer: lowerasciinormalizer
        properties:
          city:
            normalizer: lowerasciinormalizer
            type: keyword
          ride_id:
            type: keyword
          timestamp:
            type: date
          lat:
            type: float
          long:
            type: float
- name: vehicles
  topic:
    name: movr.public.vehicles
    numPartitions: 1
    replicationFactor: 3
    config:
    - key: max.message.bytes
      value: "128000"
  sql:
    type: plain
    query: SELECT * FROM vehicles
  elasticsearch:
    index: vehicles
    mapping:
      settings:
        index.requests.cache.enable: true
        index:
          number_of_shards: 3
          number_of_replicas: 2
        analysis:
          normalizer:
            lowerasciinormalizer:
              type: custom
              filter:
              - lowercase
              - asciifolding
      mappings:
        dynamic_templates:
        - string_as_keyword:
            match_mapping_type: string
            match: '*'
            mapping:
              type: keyword
              normalizer: lowerasciinormalizer
        properties:
          id:
            type: keyword
          city:
            normalizer: lowerasciinormalizer
            type: keyword
          type:
            normalizer: lowerasciinormalizer
            type: keyword
          owner_id:
            normalizer: lowerasciinormalizer
            type: keyword
          creation_time:
            type: date
          status:
            normalizer: lowerasciinormalizer
            type: keyword
          current_location:
            normalizer: lowerasciinormalizer
            type: keyword
          ext:
            normalizer: lowerasciinormalizer
            type: object
