version: '3'

services:
  elasticsearchc01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.1
    container_name: elasticsearchc01
    environment:
    - node.name=elasticsearchc01
    - cluster.name=synker
    - discovery.seed_hosts=elasticsearchc02,elasticsearchc03
    - cluster.initial_master_nodes=elasticsearchc01,elasticsearchc02,elasticsearchc03
    - bootstrap.memory_lock=true
    - "ES_JAVA_OPTS=-Xms256M -Xmx256M"
    - http.cors.enabled=true
    - http.cors.allow-origin=*
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
    - ALL
    # privileged: true
    volumes:
    - /var/log
    - elasticsearchc01:/usr/share/elasticsearch/data
    networks:
    - synker_cluster
    restart: always
  elasticsearchc02:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.1
    container_name: elasticsearchc02
    environment:
    - node.name=elasticsearchc02
    - cluster.name=synker
    - discovery.seed_hosts=elasticsearchc01,elasticsearchc03
    - cluster.initial_master_nodes=elasticsearchc01,elasticsearchc02,elasticsearchc03
    - bootstrap.memory_lock=true
    - "ES_JAVA_OPTS=-Xms256M -Xmx256M"
    - http.cors.enabled=true
    - http.cors.allow-origin=*
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
    - ALL
    # privileged: true
    volumes:
    - /var/log
    - elasticsearchc02:/usr/share/elasticsearch/data
    networks:
    - synker_cluster
    restart: always
  elasticsearchc03:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.1
    container_name: elasticsearchc03
    environment:
    - node.name=elasticsearchc03
    - cluster.name=synker
    - discovery.seed_hosts=elasticsearchc01,elasticsearchc02
    - cluster.initial_master_nodes=elasticsearchc01,elasticsearchc02,elasticsearchc03
    - bootstrap.memory_lock=true
    - "ES_JAVA_OPTS=-Xms256M -Xmx256M"
    - http.cors.enabled=true
    - http.cors.allow-origin=*
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
    - ALL
    # privileged: true
    volumes:
    - /var/log
    - elasticsearchc03:/usr/share/elasticsearch/data
    networks:
    - synker_cluster
    restart: always
  redpandac01:
    image: docker.vectorized.io/vectorized/redpanda:v21.10.1
    container_name: redpandac01
    hostname: redpandac01
    volumes:
    - redpandac01:/var/lib/redpanda/data
    networks:
    - synker_cluster
    restart: always
    ports:
    - 8082:8082
    - 9092:9092
    #- 9644:9644
    command:
    - redpanda
    - start
    - --smp
    - "1"
    - --memory
    - 1G
    - --reserve-memory
    - 0M
    - --overprovisioned
    - --node-id
    - "0"
    - --check=false
    - --pandaproxy-addr
    - 0.0.0.0:8082
    - --advertise-pandaproxy-addr
    - 0.0.0.0:8082
    - --kafka-addr
    - 0.0.0.0:9092
    - --advertise-kafka-addr
    - 0.0.0.0:9092
    - --rpc-addr
    - 0.0.0.0:33145
    - --advertise-rpc-addr
    - redpandac01:33145
  redpandac02:
    image: docker.vectorized.io/vectorized/redpanda:v21.10.1
    container_name: redpandac02
    hostname: redpandac02
    volumes:
    - redpandac02:/var/lib/redpanda/data
    networks:
    - synker_cluster
    restart: always
    ports:
    - 9093:9093
    command:
    - redpanda
    - start
    - --smp
    - "1"
    - --memory
    - 1G
    - --reserve-memory
    - 0M
    - --overprovisioned
    - --node-id
    - "1"
    - --seeds
    - redpandac01:33145
    - --check=false
    - --pandaproxy-addr
    - 0.0.0.0:8083
    - --advertise-pandaproxy-addr
    - 0.0.0.0:9093
    - --kafka-addr
    - 0.0.0.0:9093
    - --advertise-kafka-addr
    - 0.0.0.0:9093
    - --rpc-addr
    - 0.0.0.0:33146
    - --advertise-rpc-addr
    - redpandac02:33146
  redpandac03:
    image: docker.vectorized.io/vectorized/redpanda:v21.10.1
    container_name: redpandac03
    hostname: redpandac03
    volumes:
    - redpandac03:/var/lib/redpanda/data
    networks:
    - synker_cluster
    restart: always
    ports:
    - 9094:9094
    command:
    - redpanda
    - start
    - --smp
    - "1"
    - --memory
    - 1G
    - --reserve-memory
    - 0M
    - --overprovisioned
    - --node-id
    - "2"
    - --seeds
    - redpandac01:33145
    - --check=false
    - --pandaproxy-addr
    - 0.0.0.0:8084
    - --advertise-pandaproxy-addr
    - 0.0.0.0:8084
    - --kafka-addr
    - 0.0.0.0:9094
    - --advertise-kafka-addr
    - 0.0.0.0:9094
    - --rpc-addr
    - 0.0.0.0:33147
    - --advertise-rpc-addr
    - redpandac03:33147
  haproxy:
    image: haproxy:2.4-bullseye
    container_name: haproxy
    depends_on:
    - elasticsearchc01
    - elasticsearchc02
    - elasticsearchc03
    ports:
    - 1936:1936   # haproxy stats
    - 9200:9200   # elasticsearch cluster
    #- 8082:8082   # redpanda proxy
    #- 9092:9092   # redpanda kafka
    volumes:
    - ./haproxy_cluster.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    networks:
    - synker_cluster

networks:
  synker_cluster:

volumes:
  elasticsearchc01:
  elasticsearchc02:
  elasticsearchc03:
  redpandac01:
  redpandac02:
  redpandac03:
  cockroachc01:
  cockroachc02:
  cockroachc03:
