name: Unit testing

on:
  push:
    paths-ignore:
    - 'docs/**'
    - '.github/ISSUE_TEMPLATE/**'
    branches:
    - main
  pull_request:
    paths-ignore:
    - 'docs/**'
    - '.github/ISSUE_TEMPLATE/**'
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go:
        - '1.23.5'
    env:
      GOLANGCI_LINT_VERSION: 1.63.4
      COCKROACHDB_VERSION: 24.3.1
      REDPANDA_RPK_VERSION: 24.3.2

    steps:
    - uses: actions/checkout@v4 # https://github.com/actions/checkout/releases

    - name: Set up Go environment
      uses: actions/setup-go@v5 # https://github.com/actions/setup-go/releases
      with:
        go-version: ${{ matrix.go }}

    - name: Install golangci-lint
      run: |
        wget -O /tmp/golangci-lint.deb https://github.com/golangci/golangci-lint/releases/download/v${GOLANGCI_LINT_VERSION}/golangci-lint-${GOLANGCI_LINT_VERSION}-linux-amd64.deb
        sudo dpkg -i /tmp/golangci-lint.deb

    - name: Run golangci-lint
      run: golangci-lint run

    - name: Install CockroachDB
      run: |
        sudo mkdir -p /usr/local/lib/cockroach
        cd /tmp
        wget -O /tmp/cockroach-v${COCKROACHDB_VERSION}.linux-amd64.tgz https://binaries.cockroachdb.com/cockroach-v${COCKROACHDB_VERSION}.linux-amd64.tgz
        tar -xf cockroach-v${COCKROACHDB_VERSION}.linux-amd64.tgz
        sudo mv cockroach-v${COCKROACHDB_VERSION}.linux-amd64/cockroach /usr/local/bin/cockroach
        sudo mv cockroach-v${COCKROACHDB_VERSION}.linux-amd64/lib/libgeos.so /usr/local/lib/cockroach
        sudo mv cockroach-v${COCKROACHDB_VERSION}.linux-amd64/lib/libgeos_c.so /usr/local/lib/cockroach

    - name: Install redpanda rpk
      run: |
        cd /tmp
        wget -O /tmp/rpk-linux-amd64.zip https://github.com/redpanda-data/redpanda/releases/download/v${REDPANDA_RPK_VERSION}/rpk-linux-amd64.zip
        sudo unzip rpk-linux-amd64.zip -d /usr/local/bin

    - name: Setup sysctl
      run: |
        cat <<EOF | sudo tee -a /etc/sysctl.d/10-custom.conf
        vm.max_map_count=262144
        net.ipv6.conf.all.disable_ipv6=1
        net.ipv6.conf.default.disable_ipv6=1
        net.ipv6.conf.lo.disable_ipv6=1
        EOF
        sudo sysctl -p /etc/sysctl.d/10-custom.conf

    - name: Start CockroachDB single node
      run: |
        cockroach start-single-node --insecure --http-addr 0.0.0.0:8090 --background
        cockroach sql --insecure -e "SET CLUSTER SETTING kv.rangefeed.enabled = true;"
        cockroach workload run movr --duration=1m --init

    - name: Start docker-compose stack
      run: |
        sudo docker compose -f docker/cockroach-demo/docker-compose.yaml up -d
        sudo docker compose -f docker/cockroach-demo/docker-compose.yaml ps

    - name: Waiting for elasticsearch to be up
      run: |
        export SYNKER_ELASTICSEARCH_URI="http://127.0.0.1:9200"

        attempt_counter=0
        max_attempts=10

        until $(curl --output /dev/null --silent --head --fail ${SYNKER_ELASTICSEARCH_URI})
        do
          if [ ${attempt_counter} -eq ${max_attempts} ];then
            echo "Max attempts reached"
            exit 1
          fi

          printf '.'
          attempt_counter=$(($attempt_counter+1))
          sleep 5
        done

    - name: Waiting for redpanda to be up
      run: |
        export SYNKER_KAFKA_URI="127.0.0.1:19092"
        # this is to find the correct controller for this cluster
        export SYNKER_KAFKA_PORT=$(rpk cluster metadata --brokers $SYNKER_KAFKA_URI |grep '*' | awk '{print $NF}')
        export SYNKER_KAFKA_URI="127.0.0.1:${SYNKER_KAFKA_PORT}"
        echo "SYNKER_KAFKA_URI ${SYNKER_KAFKA_URI}"
        attempt_counter=0
        max_attempts=10

        until $(nc -vz localhost ${SYNKER_KAFKA_PORT} &> /dev/null)
        do
          if [ ${attempt_counter} -eq ${max_attempts} ];then
            echo "Max attempts reached"
            exit 1
          fi

          printf '.'
          attempt_counter=$(($attempt_counter+1))
          sleep 5
        done

    - name: Run unit testing
      run: |
        export SYNKER_PG_URI="postgres://root:@127.0.0.1:26257/movr?sslmode=disable"
        export SYNKER_ELASTICSEARCH_URI="http://127.0.0.1:9200"
        export SYNKER_KAFKA_URI="127.0.0.1:19092"
        echo "SYNKER_KAFKA_URI ${SYNKER_KAFKA_URI}"

        mkdir -p .coverage/global
        SYNKER_LOG_LEVEL=debug go test -v ./... -cover -args -test.gocoverdir=$PWD/.coverage/global

        mkdir -p .coverage/os_variables
        SYNKER_LOG_LEVEL=debug go test -v ./... -run TestMain_fail_api_os_variables -cover -args -test.gocoverdir=$PWD/.coverage/os_variables

    - name: Run test coverage
      run: |
        COVERAGE_DIR=$(find .coverage -type d |tail -n +2 | tr -s "\n" "," | sed 's#,$##g')
        go tool covdata textfmt -i=${COVERAGE_DIR} -o=$PWD/.coverage/coverage.out
        go tool cover -func=.coverage/coverage.out
