name: Unit testing

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go:
        - '1.22.5'
    env:
      GOLANGCI_LINT_VERSION: 1.59.1
      COCKROACHDB_VERSION: 24.1.1
    steps:
    - uses: actions/checkout@v4 # https://github.com/actions/checkout/releases

    - name: Set up Go environment
      uses: actions/setup-go@v5 # https://github.com/actions/setup-go/releaseshttps://github.com/actions/setup-go/releases
      with:
        go-version: ${{ matrix.go }}

    - name: Install golangci-lint
      run: |
        wget -O /tmp/golangci-lint.deb https://github.com/golangci/golangci-lint/releases/download/v${GOLANGCI_LINT_VERSION}/golangci-lint-${GOLANGCI_LINT_VERSION}-linux-amd64.deb
        sudo dpkg -i /tmp/golangci-lint.deb

    - name: Install CockroachDB
      run: |
        mkdir -p /usr/local/lib/cockroach
        cd /tmp
        wget -O /cockroach-v{{ COCKROACHDB_VERSION }}.linux-amd64.tgz https://binaries.cockroachdb.com/cockroach-v{{ COCKROACHDB_VERSION }}.linux-amd64.tgz
        sudo mv cockroach-v{{ COCKROACHDB_VERSION }}.linux-amd64/cockroach /usr/local/bin/cockroach
        sudo mv cockroach-v{{ COCKROACHDB_VERSION }}.linux-amd64/lib/libgeos.so /usr/local/lib/cockroach
        sudo mv cockroach-v{{ COCKROACHDB_VERSION }}.linux-amd64/lib/libgeos_c.so /usr/local/lib/cockroach

    - name: Setup sysctl
      run: |
        cat <<EOF | sudo tee -a /etc/sysctl.d/10-custom.conf
        vm.max_map_count=262144
        EOF
        sudo sysctl -p /etc/sysctl.d/10-custom.conf

    - name: Start CockroachDB demo cluster
      run: |
        cockroach demo movr --insecure --http-port 8090 & disown -h

    - name: Start docker-compose stack
      run: |
        sudo docker-compose -f docker/cockroach-demo/docker-compose.yaml up -d

    - name: Run golangci-lint
      run: golangci-lint run

    - name: Run unit testing
      run: |
        export COCKROACH_HOST=$(netstat -latn |grep 26257 |grep LISTEN |awk '{print $4}' | head -1)
        export SYNKER_PG_URI="postgres://root:@${COCKROACH_HOST}/movr?sslmode=disable"
        export SYNKER_ELASTICSEARCH_URI="http://127.0.0.1:9200"
        export SYNKER_KAFKA_URI="localhost:9092"

        SYNKER_LOG_LEVEL=debug go test -v ./... -cover -coverprofile=coverage.out  && go tool cover -html=coverage.out
        go tool cover -func=coverage.out
