name: Unit testing

on:
  workflow_call:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  call-workflow-golangci:
    uses: ./.github/actions/golangci
  call-workflow-unit-testing:
    uses: ./.github/actions/unit-testing
  call-workflow-test-coverage:
    uses: ./.github/actions/coverage
