name: Unit testing

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go:
        - '1.23.3'
    steps:
    - uses: actions/checkout@v4 # https://github.com/actions/checkout/releases

    - name: Set up Go environment
      uses: actions/setup-go@v5 # https://github.com/actions/setup-go/releases
      with:
        go-version: ${{ matrix.go }}

    - uses: ./.github/workflows/golangci.yml
    - uses: ./.github/workflows/unit-testing.yml
    - uses: ./.github/workflows/coverage.yml
