name: Unit testing

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go:
        - '1.23.3'
    steps:
    - uses: ./.github/workflows/golangci.yml
    - uses: ./.github/workflows/unit-testing.yml
    - uses: ./.github/workflows/coverage.yml
