name: Unit testing

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  tests:
    steps:
    - uses: ./.github/workflows/golangci.yml
    - uses: ./.github/workflows/unit-testing.yml
    - uses: ./.github/workflows/coverage.yml
