name: Unit testing

on:
  workflow_call:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  call-workflow-golangci:
    uses: .github/jobs/golangci.yml
  call-workflow-unit-testing:
    uses: .github/jobs/unit_testing.yml
  call-workflow-test-coverage:
    uses: .github/jobs/coverage.yml
